name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Test jq tool
        run: |
          echo '{"fruit":{"name":"apple","color":"green","price":1.20}}' | jq '.'
